python:
  image: python:3.7
  script:
    - apt-get update -q -y
    - cd backend
    - pip install -r requirements.txt
    - python manage.py test
  except:
    - /^junk.*$/

yarn:
  image: node:11
  script:
    - cd webapp
    - yarn
    - yarn build
  except:
    - /^junk.*$/


