stages:
  - test
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - .pip

npm:
  stage: test
  image: cypress/base:10
  script:
    - cd webapp
    - npm install
    - npm run lint:prettier
    - npm run test:ci
    - npm run build

python:
  stage: test
  image: python:3.7
  script:
    - apt-get update -q -y
    - cd backend
    - mkdir -p .pip
    - pip --cache-dir=.pip install -r requirements.txt
    - python manage.py test
    - isort -c -rc auction
    - black --check auction

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd backend
    - dpl --provider=heroku --app=auksjonsbua-backend --api-key=$HEROKU_API_KEY
    - cd ../webapp
    - dpl --provider=heroku --app=auksjonsbua --api-key=$HEROKU_API_KEY
  only:
    - prod
