python:
  image: python:3.7
  script:
    - apt-get update -q -y
    - cd backend
    - pip install -r requirements.txt
    - python manage.py test
    - isort -c -rc auction
    - black --check auction
  except:
    - /^junk.*$/

npm:
  image: node:11
  script:
    - cd webapp
    - npm install
    - npm run lint:prettier
    - npm build
  except:
    - /^junk.*$/
