python:
  image: python:3.7
  script:
    - apt-get update -q -y
    - cd matega_backend
    - pip install -r requirements.txt
    - python manage.py test
  except:
    - /^junk.*$/

yarn:
  image: node:11
  script:
    - cd matega_webapp
    - yarn
    - yarn lint:prettier
    - yarn lint:eslint
    - yarn build
  except:
    - /^junk.*$/


