# .gitlab-ci.yml 
# Docker Image location on hub.docker.com, its normally your-username/repo-name
image: node:11
# pipeline will use this image unless specifed in the stage definition

# Define the stages
stages:
  - test
  - build


# Define the process for each stage
test:
  stage: test
  script:
  - npm install <webapp/package.json>
  

build:
    stage: build
    script: 
    -npm install