export const authTypes = {
  INIT: "AUTH_INIT",
  LOGIN: "AUTH_LOGIN",
  FAIL: "AUTH_FAIL",
  LOGOUT: "AUTH_LOGOUT"
};

export const userTypes = {
  INIT: "USER_INIT",
  FAIL: "USER_FAIL",
  GET_USER_PROFILE: "USER_GET_PROFILE"
};

export const auctionTypes = {
  INIT: "AUCTION_INIT",
  FAIL: "AUCTION_FAIL",
  GET_AUCTION: "AUCTION_GET_AUCTION",
  GET_AUCTIONS: "AUCTION_GET_AUCTIONS",
  CREATE_AUCTION: "AUCTION_CREATE_AUCTION",
  CREATE_BID: "AUCTION_CREATE_BID"
};

export const reportTypes ={
  REPORT: "CREATE_REPORT"
}
