# Generated by Django 2.1.5 on 2019-03-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reports", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="reportDescription",
            new_name="report_description",
        )
    ]
