# Generated by Django 2.1.5 on 2019-02-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auctions", "0002_auto_20190226_2251")]

    operations = [
        migrations.CreateModel(
            name="AuctionImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="auctions")),
            ],
        ),
        migrations.RemoveField(model_name="auction", name="img"),
        migrations.AddField(
            model_name="auctionimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="auctions.Auction",
            ),
        ),
    ]
