# Generated by Django 2.1.5 on 2019-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("auctions", "0004_auto_20190227_1330")]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
