# Generated by Django 2.1.5 on 2019-03-21 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctions", "0005_auto_20190227_2253"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction", name="is_active"),
        migrations.RemoveField(model_name="auction", name="winner"),
        migrations.AddField(
            model_name="auction",
            name="_winner",
            field=models.ForeignKey(
                db_column="winner",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
